# docker-compose.yml

version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  fastapi:
    build: 
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - rabbitmq
    networks:
      - app-network
    volumes:
       - ./data:/app/data

  celery_worker:
    build: 
      context: .
      dockerfile: app/worker/Dockerfile
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - rabbitmq
      - fastapi
    networks:
      - app-network
    volumes:
      - ./data:/app/data

      
networks:
  app-network:
    driver: bridge
